dist: bionic

language: node_js

env:
  global:
    - CC_TEST_REPORTER_ID=392d81eceba03e3a8d6faaa76af25bfc402e1b6b41bc55d9c3fbedc9ffb34462

node_js:
  - 15

cache:
  yarn: true

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - yarn lint
  - yarn test:unit

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
